// app/src/app/about/about.component.ts
// @ts-nocheck

import { Component, OnInit } from '@angular/core';
import { fetchIsAuthoring, initInContextEditing, getICEAttributes }  from '@craftercms/experience-builder';

import { getModel } from '../lib/api';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  public model: any = {};
  public attributes: {[attrName: string]: string} = {};

  constructor() {
  }

  ngOnInit(): void {
    getModel('/site/website/about/index.xml').then(model => {
      this.model = model;
      const attributes = getICEAttributes({ model, fieldId: 'title_s' });
      this.attributes = attributes;

      fetchIsAuthoring().then((isAuthoring: boolean) => {
        if (isAuthoring && this.model && this.model.craftercms) {
          initInContextEditing({
            path: this.model.craftercms.path
          });
        }
      });
    });
  }
}

<h1
  [attr.data-craftercms-model-id]="attributes['data-craftercms-model-id']"
  [attr.data-craftercms-model-path]="attributes['data-craftercms-model-path']"
  [attr.data-craftercms-field-id]="'title_s'"
  [attr.data-craftercms-label]="attributes['data-craftercms-label']"
>
  {{ model['title_s'] }}
</h1>

// app/pages/about.vue
<template>
  <v-row>
    <v-col class="text-center">
      <img src="/craftercms.png" alt="CrafterCMS" class="mb-5" />
      <h1
        v-bind="getIce({ model, fieldId: 'title_s' })"
      >
        {{model.title_s}}
      </h1>
    </v-col>
  </v-row>
</template>

<script>
import { fetchIsAuthoring, initInContextEditing }  from '@craftercms/experience-builder';
import { getModel } from '../lib/api';

export default {
  name: 'AboutPage',
  async asyncData() {
    const model = await getModel('/site/website/about/index.xml');
    return { model };
  },
  async mounted() {
    const isAuthoring = await fetchIsAuthoring();
    if (isAuthoring) {
      initInContextEditing({
        path: this.model.craftercms.path
      });
    }
  }
}
</script>
